name: cognoma-machine-learning
dependencies:
- conda-forge::altair=1.2.0
- conda-forge::vega=0.4.4
- jupyter=1.0.0
- nomkl
- numexpr=2.6.2
- numpy=1.13.0
- pandas=0.20.2
- python=3.5.3
- requests=2.14.2
- scikit-learn=0.18.1
- scipy=0.19.0
- seaborn=0.7.1
- setuptools=27.2.0
- statsmodels=0.8.0
- pip:
  - neo4j-driver==1.3.1
